/* Alchemist service worker: offline app shell, cached reference data, PubChem/Wikimedia data and images. */
// The block between the markers is generated by `npm run build`. Do not edit it by hand.
// @precache-start
const VERSION = '6ad236be2d1e';
const PRECACHE = [
  './',
  'assets/brand/apple-touch-icon.png',
  'assets/brand/favicon-48.png',
  'assets/brand/icon-192.png',
  'assets/brand/icon-512.png',
  'assets/brand/icon-maskable-512.png',
  'assets/brand/logo.png',
  'assets/fonts/OFL.txt',
  'assets/fonts/plus-jakarta-sans.ttf',
  'css/alchemist.css',
  'css/explorer.css',
  'css/layouts.css',
  'css/style.css',
  'css/support.css',
  'data/classes.json',
  'data/ions/index.json',
  'data/isotopes.json',
  'data/molecules/depict.json',
  'data/molecules/index.json',
  'index.html',
  'js/app.js',
  'js/components/bohr.js',
  'js/components/cards.js',
  'js/components/common.js',
  'js/components/depict.js',
  'js/components/ghs.js',
  'js/components/icons.js',
  'js/components/layout.js',
  'js/components/moleculeViewer3D.js',
  'js/components/quiz.js',
  'js/components/richtext.js',
  'js/config.js',
  'js/core/dom.js',
  'js/core/prefs.js',
  'js/core/print.js',
  'js/core/router.js',
  'js/core/storage.js',
  'js/core/userdata.js',
  'js/data/classes.js',
  'js/data/curatedMolecules.js',
  'js/data/curriculum.js',
  'js/data/geometry.js',
  'js/data/glossary-more.js',
  'js/data/glossary-more2.js',
  'js/data/glossary-more3.js',
  'js/data/glossary.js',
  'js/data/ions.js',
  'js/data/materials.js',
  'js/data/molecules/anorganik.js',
  'js/data/molecules/biomolekul.js',
  'js/data/molecules/obat-material.js',
  'js/data/molecules/organik.js',
  'js/data/molecules/unsur.js',
  'js/data/ontology.js',
  'js/data/periodicTable.js',
  'js/data/reactionLibrary.js',
  'js/data/reactions.js',
  'js/data/references.js',
  'js/data/sectionTitles.js',
  'js/data/topics/analitik.js',
  'js/data/topics/anorganik.js',
  'js/data/topics/antarmolekul.js',
  'js/data/topics/asam-basa.js',
  'js/data/topics/atom.js',
  'js/data/topics/bentuk.js',
  'js/data/topics/biomolekul.js',
  'js/data/topics/elektrokimia.js',
  'js/data/topics/gugus-fungsi.js',
  'js/data/topics/ikatan.js',
  'js/data/topics/index.js',
  'js/data/topics/ion.js',
  'js/data/topics/karbon.js',
  'js/data/topics/kesetimbangan.js',
  'js/data/topics/kuantum.js',
  'js/data/topics/laju.js',
  'js/data/topics/larutan.js',
  'js/data/topics/lingkungan.js',
  'js/data/topics/material.js',
  'js/data/topics/meta.js',
  'js/data/topics/nuklir.js',
  'js/data/topics/order.js',
  'js/data/topics/partikel.js',
  'js/data/topics/periodik.js',
  'js/data/topics/reaksi-organik.js',
  'js/data/topics/reaksi.js',
  'js/data/topics/redoks.js',
  'js/data/topics/spektroskopi.js',
  'js/data/topics/stoikiometri.js',
  'js/data/topics/termodinamika.js',
  'js/data/topics/termokimia.js',
  'js/data/topics/zat.js',
  'js/i18n/ui.js',
  'js/labs/gas.js',
  'js/labs/kit.js',
  'js/labs/kristal.js',
  'js/labs/laju.js',
  'js/labs/nyala.js',
  'js/labs/orbital.js',
  'js/labs/paruh.js',
  'js/labs/ph.js',
  'js/labs/rakit.js',
  'js/labs/setara.js',
  'js/labs/stoikiometri.js',
  'js/labs/titrasi.js',
  'js/labs/volta.js',
  'js/labs/vsepr.js',
  'js/labs/wujud.js',
  'js/pages/about.js',
  'js/pages/around.js',
  'js/pages/assignment.js',
  'js/pages/atom.js',
  'js/pages/classes.js',
  'js/pages/compare.js',
  'js/pages/dukung.js',
  'js/pages/explore.js',
  'js/pages/glossary.js',
  'js/pages/home.js',
  'js/pages/ion.js',
  'js/pages/isotope.js',
  'js/pages/lab.js',
  'js/pages/learn.js',
  'js/pages/material.js',
  'js/pages/molecule.js',
  'js/pages/peta.js',
  'js/pages/quiz.js',
  'js/pages/reaction.js',
  'js/pages/saved.js',
  'js/pages/search.js',
  'js/pages/table.js',
  'js/pages/teacher.js',
  'js/services/bgCanvas.js',
  'js/services/data.js',
  'js/services/elementview.js',
  'js/services/formula.js',
  'js/services/identify.js',
  'js/services/lattice.js',
  'js/services/lookup.js',
  'js/services/nuclide.js',
  'js/services/pubchem.js',
  'js/services/pugview.js',
  'js/services/speech.js',
  'js/services/wiki.js',
  'manifest.webmanifest',
];
// @precache-end

const APP_CACHE = `alchemist-app-${VERSION}`;
const RUNTIME_CACHE = 'alchemist-runtime-v1';
const DATA_CACHE = 'alchemist-data-v1';
const LIVE_CACHE = 'alchemist-live-v1';
const IMAGE_CACHE = 'alchemist-images-v1';
const LIMITS = { [LIVE_CACHE]: 600, [IMAGE_CACHE]: 500, [RUNTIME_CACHE]: 120 };
const LIVE_HOSTS = [
  'pubchem.ncbi.nlm.nih.gov',
  'www.wikidata.org',
  'query.wikidata.org',
  'commons.wikimedia.org',
];
const IMAGE_HOSTS = ['upload.wikimedia.org', 'thumb.wikimedia.org'];
// "/" or, when the app is published in a subdirectory, "/that/directory/".
const SCOPE_PATH = new URL(self.registration.scope).pathname;

self.addEventListener('install', event => {
  event.waitUntil(
    caches
      .open(APP_CACHE)
      .then(cache => cache.addAll(PRECACHE.map(path => new Request(path, { cache: 'reload' }))))
  );
});

self.addEventListener('activate', event => {
  event.waitUntil(
    (async () => {
      const keep = new Set([APP_CACHE, RUNTIME_CACHE, DATA_CACHE, LIVE_CACHE, IMAGE_CACHE]);
      for (const key of await caches.keys())
        if (key.startsWith('alchemist-') && !keep.has(key)) await caches.delete(key);
      await self.clients.claim();
    })()
  );
});

self.addEventListener('message', event => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});

async function trim(cacheName) {
  const limit = LIMITS[cacheName];
  if (!limit) return;
  const cache = await caches.open(cacheName);
  const keys = await cache.keys();
  for (let i = 0; i < keys.length - limit; i++) await cache.delete(keys[i]);
}

const timeout = ms => new Promise((_, reject) => setTimeout(() => reject(new Error('timeout')), ms));

/** Network first (fresh when online), falling back to the last good copy. */
async function networkFirst(request, cacheName, wait = 10000) {
  const cache = await caches.open(cacheName);
  try {
    const response = await Promise.race([fetch(request), timeout(wait)]);
    if (response.ok) cache.put(request, response.clone()).then(() => trim(cacheName));
    return response;
  } catch (error) {
    const cached = await cache.match(request, { ignoreVary: true });
    if (cached) return cached;
    throw error;
  }
}

/** Cache first, refreshed in the background (app files that change between versions). */
async function staleWhileRevalidate(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);
  const refresh = fetch(request)
    .then(response => {
      if (response.ok) cache.put(request, response.clone()).then(() => trim(cacheName));
      return response;
    })
    .catch(() => cached);
  return cached || refresh;
}

/** Images: cache first, fetched with CORS so cached entries stay small. */
async function imageCacheFirst(request) {
  const cache = await caches.open(IMAGE_CACHE);
  const cached = await cache.match(request.url);
  if (cached) return cached;
  try {
    const response = await fetch(request.url, { mode: 'cors', credentials: 'omit' });
    if (response.ok) cache.put(request.url, response.clone()).then(() => trim(IMAGE_CACHE));
    return response;
  } catch {
    return fetch(request);
  }
}

self.addEventListener('fetch', event => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);

  if (url.origin === self.location.origin) {
    if (request.mode === 'navigate') {
      event.respondWith(networkFirst(request, APP_CACHE, 5000).catch(() => caches.match('index.html')));
      return;
    }
    // Reference data and the PubChem proxy: fresh when online, cached for offline use. Paths are matched
    // relative to the app, so the precached js/data/ modules are not mistaken for reference data.
    const path = url.pathname.startsWith(SCOPE_PATH) ? url.pathname.slice(SCOPE_PATH.length) : url.pathname;
    if (path.startsWith('data/') || path.startsWith('api/')) {
      event.respondWith(networkFirst(request, path.startsWith('api/') ? LIVE_CACHE : DATA_CACHE));
      return;
    }
    event.respondWith(
      caches
        .match(request, { ignoreSearch: true })
        .then(hit => hit || staleWhileRevalidate(request, RUNTIME_CACHE))
    );
    return;
  }
  if (url.hostname === 'pubchem.ncbi.nlm.nih.gov' && url.pathname.endsWith('/PNG')) {
    event.respondWith(imageCacheFirst(request));
    return;
  }
  if (LIVE_HOSTS.includes(url.hostname) || url.hostname.endsWith('.wikipedia.org')) {
    event.respondWith(networkFirst(request, LIVE_CACHE));
    return;
  }
  if (IMAGE_HOSTS.includes(url.hostname)) event.respondWith(imageCacheFirst(request));
});
