#!/usr/bin/env node
// Regenerates js/data/sectionTitles.js: the official titles of the OpenStax sections Alchemist cites (lessons,
// reactions, materials, ions and knowledge-map domains), read from scripts/data/openstax-sections.json. Only cited
// sections are copied, so the app does not ship the whole table of contents. Run by `npm run build`; `--check`
// fails when the file is out of date.
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { TOPIC_ORDER } from '../js/data/topics/order.js';
import { ALL_REACTIONS } from '../js/data/reactionLibrary.js';
import { MATERIALS } from '../js/data/materials.js';
import { IONS } from '../js/data/ions.js';
import { DOMAINS } from '../js/data/ontology.js';

// Reference-code prefixes (as in js/data/references.js, which imports the generated file, so it is not imported here).
const BOOKS = { chem: 'chemistry-2e', oc: 'organic-chemistry', bio: 'biology-2e' };

const sections = JSON.parse(
  await readFile(new URL('./data/openstax-sections.json', import.meta.url), 'utf8')
).books;
const topics = await Promise.all(
  TOPIC_ORDER.map(id => import(`../js/data/topics/${id}.js`).then(m => m.default))
);
const codes = new Set(
  [
    ...topics.flatMap(t => t.refs || []),
    ...ALL_REACTIONS.flatMap(r => r.src || []),
    ...MATERIALS.flatMap(m => m.src || []),
    ...IONS.flatMap(i => i.src || []),
    ...DOMAINS.flatMap(d => d.src || []),
  ].filter(c => !String(c).startsWith('wiki:'))
);

const titles = {};
const unknown = [];
for (const code of [...codes].sort()) {
  const [prefix, slug] = code.includes(':') ? code.split(':') : ['chem', code];
  const title = sections[BOOKS[prefix]]?.[slug];
  if (title) titles[code] = title;
  else unknown.push(code);
}
if (unknown.length)
  console.warn(`Not in openstax-sections.json (see npm run data:check): ${unknown.join(', ')}`);

const out = `// GENERATED by scripts/build-refs.mjs from scripts/data/openstax-sections.json. Do not edit: run \`npm run build\`.
// Official titles of the OpenStax sections Alchemist cites, by reference code (see references.js).
export const SECTION_TITLES = {
${Object.entries(titles)
  .map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`)
  .join('\n')}
};
`;
const file = fileURLToPath(new URL('../js/data/sectionTitles.js', import.meta.url));
let current = '';
try {
  current = await readFile(file, 'utf8');
} catch {
  // First run: the file does not exist yet.
}
if (process.argv.includes('--check')) {
  if (current !== out) {
    console.error('js/data/sectionTitles.js is out of date. Run `npm run build`.');
    process.exit(1);
  }
  console.log(`sectionTitles.js is up to date (${Object.keys(titles).length} sections).`);
} else {
  await writeFile(file, out);
  console.log(`sectionTitles.js: ${Object.keys(titles).length} cited sections`);
}
