#!/usr/bin/env node
// Regenerates js/data/topics/meta.js (the light index every page loads) from the topic files, so a lesson's
// title, summary and levels are written only once. Lesson bodies, quizzes and teacher notes stay in the topic
// files and load on demand. `links` indexes what each lesson mentions (elements, molecules, ions, reactions,
// materials, glossary terms, labs) so element, molecule and other pages can point back to the lessons about them.
// Run by `npm run build`; `--check` fails when meta.js is out of date.
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { TOPIC_ORDER } from '../js/data/topics/order.js';
import { findTerm } from '../js/data/glossary.js';

const dir = fileURLToPath(new URL('../js/data/topics/', import.meta.url));
const LAYERS = ['sd', 'smp', 'sma', 'kuliah'];
const LINK = /\{\{(m|e|i|r|mat|lab):([^}|]+)(?:\|[^}]+)?\}\}/g;
const TERM = /\[\[([^\]|]+)(?:\|[^\]]+)?\]\]/g;

/** Every string inside a value (lesson layers, points, activities). */
const texts = value =>
  typeof value === 'string'
    ? [value]
    : value && typeof value === 'object'
      ? Object.values(value).flatMap(texts)
      : [];

/** { e: ['Fe'], m: ['water'], i: [], r: [], mat: [], g: ['ion'], lab: ['nyala'] }, empty kinds left out. */
function linksOf(t) {
  const found = {
    e: new Set(),
    m: new Set(t.molecules || []),
    i: new Set(),
    r: new Set(),
    mat: new Set(),
    g: new Set(),
    lab: new Set(t.labs || []),
  };
  for (const text of texts([t.body, t.points, t.activity])) {
    for (const [, kind, id] of text.matchAll(LINK)) found[kind].add(id.trim());
    for (const [, key] of text.matchAll(TERM)) {
      const term = findTerm(key.trim());
      if (term) found.g.add(term.key);
    }
  }
  return Object.fromEntries(
    Object.entries(found)
      .filter(([, set]) => set.size)
      .map(([kind, set]) => [kind, [...set].sort()])
  );
}

const meta = [];
for (const id of TOPIC_ORDER) {
  const t = (await import(pathToFileURL(join(dir, `${id}.js`)).href)).default;
  if (t.id !== id) throw new Error(`${id}.js declares id "${t.id}"`);
  meta.push({
    id,
    icon: t.icon,
    levels: t.levels,
    layers: LAYERS.filter(l => t.body[l]),
    title: t.title,
    summary: t.summary,
    nQuiz: t.quiz.length,
    links: linksOf(t),
  });
}
const out = `// GENERATED by scripts/build-topics.mjs from the topic files. Do not edit: run \`npm run build\`.
// layers = levels with lesson text · levels = levels the topic is recommended for · nQuiz = number of questions ·
// links = what the lesson mentions (e element, m molecule, i ion, r reaction, mat material, g glossary, lab).
export const META = [
${meta.map(m => `  ${JSON.stringify(m)},`).join('\n')}
];
`;
const file = join(dir, 'meta.js');
let current = '';
try {
  current = await readFile(file, 'utf8');
} catch {
  // First run: meta.js does not exist yet.
}
if (process.argv.includes('--check')) {
  if (current !== out) {
    console.error('js/data/topics/meta.js is out of date. Run `npm run build`.');
    process.exit(1);
  }
  console.log(`topics/meta.js is up to date (${meta.length} topics).`);
} else {
  await writeFile(file, out);
  console.log(`topics/meta.js: ${meta.length} topics`);
}
