// Reference data bundled with the site (generated by the sync scripts from PubChem, Wikidata, Wikipedia
// and Commons). Cached in memory; the service worker keeps copies for offline use.
const cache = new Map();

async function json(path) {
  if (cache.has(path)) return cache.get(path);
  const task = fetch(new URL(path, document.baseURI), { signal: AbortSignal.timeout(15000) }).then(r => {
    if (!r.ok) throw new Error(`${path}: HTTP ${r.status}`);
    return r.json();
  });
  cache.set(path, task);
  task.catch(() => cache.delete(path));
  return task;
}

let indexMap = null;
let depictions = {};
/**
 * Map id → { cid, formula, mw, iupac, s (structure kind), photo, ghs } for every catalogue molecule.
 * Also loads the 2D drawings used by cards (see depiction()).
 */
export async function moleculeIndex() {
  if (indexMap) return indexMap;
  const [list, dep] = await Promise.all([
    json('data/molecules/index.json').catch(() => []),
    json('data/molecules/depict.json').catch(() => ({})),
  ]);
  depictions = dep || {};
  indexMap = new Map(list.map(r => [r.id, r]));
  return indexMap;
}
/** 2D drawing data for a catalogue molecule (available once moleculeIndex() has resolved). */
export const depiction = id => depictions[id] || null;

export const moleculeRecord = id => json(`data/molecules/${encodeURIComponent(id)}.json`);
export const elementRecord = z => json(`data/elements/${Number(z)}.json`);
export const classMembers = () => json('data/classes.json').catch(() => ({}));

let ionMap = null;
/** Map ion id → { cid, formula, charge, mw, iupac } (PubChem, checked against js/data/ions.js). */
export async function ionIndex() {
  if (ionMap) return ionMap;
  const list = await json('data/ions/index.json').catch(() => []);
  ionMap = new Map(list.map(r => [r.id, r]));
  return ionMap;
}
export const ionRecord = id => json(`data/ions/${encodeURIComponent(id)}.json`);

let isotopes = null;
/**
 * Every known nuclide's ground state (IAEA AMDC via PubChem): [{ z, A, half, seconds, stable, decay, abundance }].
 * `seconds` is null when the half-life is not known; `abundance` is the IUPAC CIAAW natural abundance text.
 */
export async function isotopeIndex() {
  if (isotopes) return isotopes;
  const data = await json('data/isotopes.json');
  isotopes = data.rows.map(([z, A, half, seconds, decay, abundance]) => ({
    z,
    A,
    half,
    seconds: seconds === -1 ? null : seconds,
    stable: seconds === -1,
    decay,
    abundance,
  }));
  return isotopes;
}

/** Formulas by id, for searching the catalogue by formula. */
export async function formulas() {
  const idx = await moleculeIndex();
  return Object.fromEntries([...idx].map(([id, r]) => [id, r.formula]));
}

/** Every data file, for "save for offline". */
export async function allDataFiles() {
  const [idx, ions] = await Promise.all([moleculeIndex(), ionIndex()]);
  return [
    'data/molecules/index.json',
    'data/molecules/depict.json',
    'data/classes.json',
    'data/ions/index.json',
    'data/isotopes.json',
    ...[...idx.keys()].map(id => `data/molecules/${id}.json`),
    ...[...ions.keys()].map(id => `data/ions/${id}.json`),
    ...Array.from({ length: 118 }, (_, i) => `data/elements/${i + 1}.json`),
  ];
}
